### ISSUE TITLE
Incremental compilation may leave empty directories when templates are removed

### ISSUE THREAD

**Issue by ldaley** [etiennestuder/gradle-rocker-plugin#9]
https://github.com/etiennestuder/gradle-rocker-plugin/blob/master/src/main/java/nu/studer/gradle/rocker/RockerCompile.java#L212

If all of the templates are removed from a directory/package for an incremental compilation, after the compiled templates are removed the corresponding directory remains. This creates a different result than if non incremental compilation was used. 

It might be enough to just walk the output directory and remove any empty dirs after an incremental compile.

**Comment by pbielicki** [comment]
Current workaround is to run Gradle task with `--no-build-cache` option

**Comment by etiennestuder** [comment]
@ldaley just to understand: in what scenarios are those empty output directories an issue?

**Comment by facewindu** [comment]
> @ldaley just to understand: in what scenarios are those empty output directories an issue?

Leaving the empty directories will generate a different cache key compared to a stock execution where the 'now removed' src directory is absent.
Said differently, one could have the same inputs as someone else, but still have a cache miss because they have a zombie empty directory in the generated rocker template folder.

**Comment by etiennestuder** [comment]
Ah yes of course. If the output of the Rocker task serves as the input to another task, this is a problem. Thanks, @facewindu .
